# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Dynamically update README.md

on:
  push:
    branches: [ "master" ]

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Run the script
      run: |
        python update_readme.py
    - name: Push to github
      run: |
        if git status | grep -q "nothing to commit"; then
          echo "No changes to commit. Exiting"
        else
          echo "Updating README.md"
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[bot] updated readme"
          git push
        fi
